mysite/main/urls.py
from django.conf.urls import url

from . import views
app_name = 'main'
urlpatterns = [
    url(r'^clear/$', views.Delete_Files, name='clear_database'),
    url(r'^upload/$', views.Upload.as_view(), name='upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf.urls import url, include


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^main/', include('mysite.main.urls', namespace='main')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/main/models.py
from __future__ import unicode_literals

from django.db import models


class Files(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='files/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

mysite/main/forms.py
from django import forms

from .models import Files


class FileForm(forms.ModelForm):
    class Meta:
        model = Files
        fields = ('file', )

mysite/main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from .forms import FileForm
from .models import Files


class Upload(View):
    def get(self, request):
        f_list = Files.objects.all()
        return render(self.request, 'main/basic_upload/index.html', {'Obj': f_list})

    def post(self, request):
        form = FileForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            f = form.save()
            data = {'is_valid': True, 'name': f.file.name, 'url': f.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def Delete_Files(request):
    for f in Files.objects.all():
        f.file.delete()
        f.delete()
    return redirect(request.POST.get('next'))

mysite/main/templates/main/base.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="page-header">
    Multiple Files Upload (Modified Admin)
  </h1>
  <div class="row">
    <div class="col-md-8">
      {% block files_content %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

mysite/main/templates/main/basic_upload/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Upload{% endblock %}

{% block javascript %}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

<script src="{% static 'main/js/basic-upload.js' %}"></script>
{% endblock %}

{% block files_content %}
<div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos"> Upload Files</button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'main:upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
</div>
<di>
    <form method="post" action="{% url 'main:clear_database' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button type="submit" class="btn btn-danger pull-right"> Delete Files
        </button>
    </form>
</di>

<table id="gallery" class="table table-bordered">
    <thead>
    <tr>
        <th>Files Details</th>
    </tr>
    </thead>
    <tbody>
    {% for f in Obj %}
    <tr>
        <td><a href="{{ f.file.url }}">{{ f.file.name }}</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

mysite/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django admin multiples file uploads{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <style type="text/css">
        .page-header {
            margin-top: 0;
        }
    </style>
</head>
<body>
{% include 'includes/header.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1 class="page-header">Multiple File Upload Example (Modified Admin)</h1>
<div>
    <p>This example will show how to upload multiples files in django admin site.</p>
</div>
{% endblock %}

mysite/templates/includes/header.html
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <a class="navbar-brand" href="{% url 'main:upload' %}">Upload Files</a>

        </div>
    </div>
</nav>